# Generated by Django 2.2 on 2019-04-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
    ]
